New method to add files from list of paths
allegroai/clearml pull request #1129
Opened 2023-10-04 16:45 UTC by CharlesFrankum

## Related Issue \ discussion
https://github.com/allegroai/clearml/issues/1127

## Patch Description
Adds a new method to allow adding files to Dataset via a list of paths

## Testing Instructions
```
from clearml import Dataset

test_dir = ''
file_paths = [f for f in listdir(test_dir) if isfile(join(test_dir , f))]
dataset.add_files_from_list(paths=paths)
```

2023-10-21 12:21 UTC, eugen-ajechiloae-clearml commented
Hi @CharlesFrankum ! I don't think we should have a new function here, but instead make `path` in `add_files` support sequences as well, similarly to how it's done in `add_external_files`: https://github.com/allegroai/clearml/blob/18210ed144ce630fb1bda44d07cea356a7e23b53/clearml/datasets/dataset.py#L436

2023-10-23 09:56 UTC, CharlesFrankum commented
> Hi @CharlesFrankum ! I don't think we should have a new function here, but instead make `path` in `add_files` support sequences as well, similarly to how it's done in `add_external_files`:
> 
> https://github.com/allegroai/clearml/blob/18210ed144ce630fb1bda44d07cea356a7e23b53/clearml/datasets/dataset.py#L436

Ah ok! I wasn't sure if we wanted to accept multiple types here but makes sense - will make the changes 👍

2023-11-07 20:29 UTC, jkhenning commented
Hi @CharlesFrankum , any update?

2023-11-08 17:20 UTC, eugen-ajechiloae-clearml requested changes
I think we can improve this a bit :+1:

2023-11-08 17:20 UTC, eugen-ajechiloae-clearml commented on clearml/datasets/dataset.py
> +                ]
let's have this section as a different function, called `def _resolve_file_entries`. Don't calculate the hashes in this function.

2023-11-08 17:20 UTC, eugen-ajechiloae-clearml commented on clearml/datasets/dataset.py
> +            file_entries = [f for f in files if f.is_file()]
Here, you should call the `_resolve_file_entries` on each path specified in `path`:
```py
if isinstance(path, (str, Path, _Path)):
    path = [path]  # ensure list
file_entries = []
for p in path:
    file_entries.extend(self._resolve_file_entries(p))

# now calculate the hashes
```

2023-11-10 14:09 UTC, eugen-ajechiloae-clearml requested changes

2023-11-10 14:09 UTC, eugen-ajechiloae-clearml commented on clearml/datasets/dataset.py
> +            file_entry = self._calc_file_hash(
No need to calculate the hash here

2024-03-07 15:29 UTC, closed without merging

2024-03-07 16:00 UTC, eugen-ajechiloae-clearml commented
Hi @CharlesFrankum ! Why was this PR closed? Any way we can help reopen it?

2024-03-07 16:47 UTC, CharlesFrankum commented
> Hi @CharlesFrankum ! Why was this PR closed? Any way we can help reopen it?

Ah sorry, I messed up my master branch on the fork so reset it so I could work on a different PR and it automatically closed this PR. I can reopen it and work on it in a little. Sorry for never finishing this one btw - we ended up moving away from clearml datasets for now so was low priority

2024-03-07 17:46 UTC, eugen-ajechiloae-clearml commented
@CharlesFrankum It would be great if we could have this PR merged. If you could reopen it that would be great. If you don't wish to work on it anymore I can take over.