WIP: add catboost
allegroai/clearml pull request #542
Opened 2022-01-18 16:00 UTC by eugen-ajechiloae-clearml

2022-01-20 15:08 UTC, JDennisJ requested changes
Looks good :) Update me if you need any help with the comments

Also please run black for formatting (max-line-length=120) :)

2022-01-20 15:08 UTC, JDennisJ commented on clearml/binding/frameworks/catboost_bind.py
> +                iteration = info['iteration']
`info.get` is safer in this case

2022-01-22 20:25 UTC, eugen-ajechiloae-clearml commented on clearml/binding/frameworks/catboost_bind.py
> +        print('got in _callback_after_iteration')
removed

2022-01-22 20:26 UTC, eugen-ajechiloae-clearml commented on clearml/binding/frameworks/catboost_bind.py
> +    def _load(original_fn, obj, f, *args, **kwargs):
function now has the same signature as in PatchBaseModelIO

2022-01-22 20:26 UTC, eugen-ajechiloae-clearml commented on clearml/binding/frameworks/catboost_bind.py
> +from ...config import running_remotely
removed

2022-01-22 20:26 UTC, eugen-ajechiloae-clearml commented on clearml/binding/frameworks/catboost_bind.py
> +        except Exception:
added

2022-01-22 20:27 UTC, eugen-ajechiloae-clearml commented on examples/frameworks/catboost/catboost_example.py
> +from sklearn.linear_model import Ridge
removed

2022-01-22 20:27 UTC, eugen-ajechiloae-clearml commented on clearml/binding/frameworks/catboost_bind.py
> +                iteration = info['iteration']
using info.get now

2022-01-23 07:30 UTC, erezalg commented
In the example's requirement.txt there are a lot of external lib imports, I suggest removing:
click, boto3, IPython, ipywidgets 
unless they are really necessary. 
BTW, if they are necessary, consider a simpler example code (instead of click use argparse, not use boto3 and not sure why would you need IPython for an example code)

2022-02-03 19:36 UTC, merged