Requirements are updated and Capitalized examples task name
allegroai/clearml pull request #573
Opened 2022-02-07 12:09 UTC by Rizwan-Hasan

- Requirements are updated  and tested using
    - Python 3.5.7
    - Python 3.6.5
    - Python 3.7.4
    - Python 3.8.7
- Capitalized the examples task name

2022-02-07 15:03 UTC, shomratalon requested changes

2022-02-07 15:03 UTC, shomratalon commented on examples/frameworks/pytorch/requirements.txt
> +jsonschema==3.2.0 ; python_version <= '3.5'
what about the case of python_version > '3.5'?

2022-02-07 15:28 UTC, Rizwan-Hasan commented on examples/frameworks/pytorch/requirements.txt
> -clearml
Mistakenly hadn't selected the clearml while copying from the testing folder.

2022-02-07 15:32 UTC, Rizwan-Hasan commented on examples/frameworks/pytorch/requirements.txt
> +jsonschema==3.2.0 ; python_version <= '3.5'
In my test, I saw pip ignored the condition and instead install suitable jsonschema automatically which is higher than the version 3.2.0.

2022-02-08 07:58 UTC, Rizwan-Hasan reviewed
added clearml

2022-02-08 13:12 UTC, Rizwan-Hasan commented
ol

2022-02-08 13:16 UTC, Rizwan-Hasan commented
- Capitalized the examples task name

2022-02-13 09:05 UTC, JDennisJ approved these changes

2022-02-14 08:18 UTC, merged